### ISSUE TITLE
IPad device can not use two fingers to enlarge and reduce canvas

### ISSUE THREAD

**Issue by wuhao4433** [Zukdoor/ZukBoard#125]
**Describe the bug**
IPad device can not use two fingers to enlarge and reduce canvas.

**To Reproduce**
1, open the whiteboard in iPad browser.
2, use double fingers to zoom on the drawing board.
3, unable to normal scale operation of the sketchpad.

**Expected behavior**
On touch-screen devices, the canvas is scaled with two fingers, and the canvas ratio should be scaled with the operation content.

**Smartphone (please complete the following information):**
 - Device: [iPad]
 - OS: [iOS11.3]
 - Browser [safari]

**Comment by lucifer1004** [comment]
Fixed.
